### ISSUE TITLE
[jd-self-support] 非首页筛选结果优化

### ISSUE THREAD

**Issue by Gslw** [gam2046/userscript#1]
1. 搜索后并不能自动只显示自营商品，需要手动打钩：仅显示京东自营商品。

2.打钩后每页自营待在各自页，1页很满，2页1个，3页2个，4页X个。。。。能弄成堆满2页么？方便浏览。

**Comment by Lua12138** [comment]
感谢。

本身只是为了方便自己用的小工具，没考虑那么多。

默认不勾选是为了不打扰默认结果，这个我自己觉得多点一下应该没什么吧。

至于第二点确实是个问题，由于京东页面默认单页最多加载120个商品信息。之后需要手动翻页。

关于这个问题暂时想法是做成单页，即随着鼠标滚轮下移会自动加载后续商品，不需要手动翻页，不过是否可行需要分析一下页面。

2017年9月17日 下午2:14，"Gslw" <notifications@github.com>写道：

**Comment by Gslw** [comment]
嗯，手动勾选也不费事倒是。第二个希望有方法解决。

发现个新的问题，脚本似乎在list页面下并不工作。

**Comment by Lua12138** [comment]
基本上单页加载完成了。魔改了京东的页脚。


不工作页面烦请给个链接。我自己只看了搜索页和分类检索页，可能还有其他页面。这个是基于URL模式匹配的。

2017年9月17日 下午5:19，"Gslw" <notifications@github.com>写道：

**Comment by Gslw** [comment]
https://list.jd.com/list.html?cat=12218,13581,13583

类似如上地址，并不显示能勾选的仅限京东自营

**Comment by Lua12138** [comment]
了解，反馈的问题 等手头工作处理掉了。搞一下。已经搞了一大半，其实快完成了。

感恩。

2017-09-17 18:33 GMT+08:00 Gslw <notifications@github.com>:

**Comment by Gslw** [comment]
嗯，新版解决了之前的问题，遇到个新的问题：

之前说不自动勾选，由用户自行选择是否看第三方，但现在决定只看自营后，每次翻页都需要再勾选一次，应该也没人会每次翻页就考虑一下是否看第三方，所以一旦勾选翻页就自动勾选这功能能实现么？

**Comment by Lua12138** [comment]
建议尝试更新（0.3.1）。新的情况是，勾选了只选自营，页脚的跳页会被我替换掉。一直是单页刷新。不存在翻页后需要再次勾选的问题。

但是你给出的那个分类检索页没有实现该功能。原因是该页面没有找到相关参数可以获得商品信息。暂时先搁置此问题。检索页与大部分分类页都是可用的。

在 2017年9月18日 下午1:59，Gslw <notifications@github.com>写道：

**Comment by Gslw** [comment]
嗯，的确是分类检索页有问题，只能先搁置了，感谢楼主分享如此实用方便的脚本。

**Comment by Lua12138** [comment]
因为自己有需求，网上找了一圈，都是有段时间没更新了，没法用。所以才自己造轮子。分类检索的情况，有时间了回去再看看。

另外有个计划，对比京东、美亚、日亚、德亚的价格曲线以及历史价格，当然历史价格的轮子以前造过，不过代码遗失了。现在的比价插件，这个广告，真是绝了。自己造个清静的。

这个轮子基本上就是这样了，只要京东网页没有变化，应该是不会动了。

2017-09-18 14:22 GMT+08:00 Gslw <notifications@github.com>:
