### ISSUE TITLE
pc端会跳到手机端页面

### ISSUE THREAD

**Issue by github-yyh** [gam2046/userscript#4]
电脑打开商品后，总是跳到手机端的页面

**Comment by Lua12138** [comment]
能否给出相关详细的环境参数，如浏览器类型、版本，复现步骤等？

**Comment by github-yyh** [comment]
我重新测试了下，似乎是和（守候购物小助手）冲突了，开你的脚本和这个插件任一个都没问题，一起开后，点开商品就会跳到手机端页面。之前是可以同时使用的，现在不知道是哪个更新后这样了。
浏览器是谷歌76.0.3809.132
复现步骤：https://miaosha.jd.com/   点击这个网址任意一个商品会跳转到手机端页面




------------------ 原始邮件 ------------------
发件人: "forDream"<notifications@github.com>; 
发送时间: 2019年9月4日(星期三) 中午1:38
收件人: "gam2046/userscript"<userscript@noreply.github.com>; 
抄送: ""<765522696@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [gam2046/userscript] pc端会跳到手机端页面 (#4)




能否给出相关详细的环境参数，如浏览器类型、版本，复现步骤等？

**Comment by Lua12138** [comment]
很遗憾，您所述的另一款工具，经搜索（https://chrome.google.com/webstore/detail/%E5%AE%88%E5%80%99%E8%B4%AD%E7%89%A9%E5%B0%8F%E5%8A%A9%E6%89%8B/eafefjbddnbamfophdiiiemfkfocaahm?hl=zh-CN ）并非开源产品，系商业公司产品（所属湖南暖桔信息科技有限公司）。

因此该问题暂时关闭，不做处理。

如果您仍然愿意协助处理此问题，请通过邮件方式，发送给我您的IM联系方式（请勿直接回复此issue，这是公开的），我会在近期较为空闲的时间，与您取得联系。

My E-Mail: gam2046#gmail.com (replace # to @)
