### ISSUE TITLE
价格查询脚本：打开商品链接会先跳转到京东热卖页面

### ISSUE THREAD

**Issue by MrEbonycat** [gam2046/userscript#5]
打开商品链接（如：https://item.jd.com/100001357738.html）会先跳转到京东热卖页面再跳转到商品页面。
       如果此时启动了返利推广链接自动清洗脚本，又会自动跳转到京东热卖。

**Comment by Lua12138** [comment]
非常抱歉对您产生了不好的体验。

关于你反馈的情况，插件描述页，有关于此描述。

https://greasyfork.org/zh-CN/scripts/37901-jd-tmall-taobao-amazon-histroy-price

您可以卸载本插件。
