### ISSUE TITLE
京东/天猫/淘宝/历史价格/优惠券

### ISSUE THREAD

**Issue by xsd116** [gam2046/userscript#8]
这个插件在京东页面使用会一直刷新一直跳，不稳定

**Comment by Lua12138** [comment]
请联系QQ 1151394385 反馈。或者详细描述使用环境
浏览器版本、具体反复跳转的页面、重现步骤等

**Comment by xsd116** [comment]
只是任意打开了一个京东商品页面，该页面包含多种分类选择的，就会这样，部分只有一个分类的似乎偶尔也会闪，有时候不闪







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gam2046/userscript"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 上午10:15
收件人:&nbsp;"gam2046/userscript"<userscript@noreply.github.com&gt;;
抄送:&nbsp;"371156280"<371156280@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gam2046/userscript] 京东/天猫/淘宝/历史价格/优惠券 (#8)





 
请联系QQ 1151394385 反馈。或者详细描述使用环境
 浏览器版本、具体反复跳转的页面、重现步骤等

**Comment by Lua12138** [comment]
依据你的方法不能重现，尝试Chrome与Microsoft Edge无此问题。也没有其他人反馈其情况。如果有更详细的信息或稳定可重现步骤时，可重新打开此工单。
